# Generated by Django 3.1.7 on 2021-02-28 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='access',
            old_name='document_id',
            new_name='document',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='username',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='document_id',
            new_name='document',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='username',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='access',
            name='role',
            field=models.CharField(choices=[('OWNER', 'owner'), ('COLLABORATOR', 'collaborator')], default='OWNER', max_length=31),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=63),
        ),
        migrations.AlterField(
            model_name='event',
            name='action',
            field=models.CharField(max_length=31),
        ),
    ]
