# Generated by Django 3.1.7 on 2021-03-01 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0003_auto_20210301_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.document'),
        ),
        migrations.AlterField(
            model_name='access',
            name='role',
            field=models.CharField(choices=[('OWNER', 'owner'), ('COLLABORATOR', 'collaborator')], default='OWNER', max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='access',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.document'),
        ),
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
