# Generated by Django 3.1.7 on 2021-03-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_auto_20210301_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='isEdit',
            field=models.BooleanField(default=False),
        ),
    ]
