# Generated by Django 3.1.7 on 2021-03-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_auto_20210301_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='document',
            field=models.UUIDField(),
        ),
    ]
